{{- if .Values.autoscaling.api.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ohmyrasp-api
  labels:
    app.kubernetes.io/name: ohmyrasp-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ohmyrasp-api
  minReplicas: {{ .Values.autoscaling.api.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.api.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.api.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.api.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
{{- if .Values.autoscaling.web.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ohmyrasp-web
  labels:
    app.kubernetes.io/name: ohmyrasp-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ohmyrasp-web
  minReplicas: {{ .Values.autoscaling.web.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.web.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.web.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.web.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
