{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohmyrasp.secretName" . }}
  labels:
    app.kubernetes.io/name: ohmyrasp-control
type: Opaque
stringData:
  OHMYRASP_POSTGRES_DSN: {{ default .Values.api.env.postgresDsn .Values.secrets.data.postgresDsn | quote }}
  OHMYRASP_CLICKHOUSE_DSN: {{ default .Values.api.env.clickhouseDsn .Values.secrets.data.clickhouseDsn | quote }}
  OHMYRASP_VALKEY_ADDR: {{ default .Values.api.env.valkeyAddr .Values.secrets.data.valkeyAddr | quote }}
  OHMYRASP_VALKEY_USERNAME: {{ default .Values.api.env.valkeyUsername .Values.secrets.data.valkeyUsername | quote }}
  OHMYRASP_VALKEY_PASSWORD: {{ default .Values.api.env.valkeyPassword .Values.secrets.data.valkeyPassword | quote }}
{{- end }}
